import type { Metadata } from "next";
import "../globals.css";
import { availableLanguageTags } from "@/paraglide/runtime";
import { Providers } from "@/app/providers";
import LanguageProvider from "@/lib/i18n/LanguageProvider";

export async function generateStaticParams() {
  return availableLanguageTags.map((lang) => ({ lang }));
}

export const metadata: Metadata = {
  title: "ShotbyNUNES - Creative Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <LanguageProvider>{children}</LanguageProvider>
    </Providers>
  );
}
