import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import { Providers } from "./providers";

const arimo = Arimo({ 
  subsets: ["latin"], 
  display: 'swap',
  variable: '--font-arimo',
});

const basement = localFont({ 
  src: '../fonts/BasementGrotesque.otf',  
  display: 'swap',
  variable: '--font-basement', 
})

export const metadata: Metadata = {
  title: "ShotbyNUNES - Creative Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body className={`${arimo.className} ${arimo.variable} ${basement.className} ${basement.variable}`}>
        <Providers>
            {children}
        </Providers>
      </body>
    </html>
  );
}
